name: Terraform CD

on:
    pull_request:
        branches: [ "main" ]
        paths:
            - 'terraform/*'

jobs:
    Terraform-CD:
        runs-on: ubuntu-latest

        # Working DIR for all terraform commands 
        defaults:
            run:
                working-directory: terraform
        
        steps:
            # Checking out repo code
            -   name: Checkout
                uses: actions/checkout@v4

            # Setup Terraform for use in workflows
            -   name: Setup TF
                uses: hashicorp/setup-terraform@v3

            # Configuring AWS secrets for authentication
            -   name: Configure AWS Cred
                uses: aws-actions/configure-aws-credentials@v2
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                    aws-region: us-east-1

            # TF initializing
            -   name: Terraform init
                run: terraform init

            # Generate and display TF exec plan
            -   name: Terraform Plan
                run: terraform plan